dataset_creation_robot:
    img_topics:
        - '/camera/color/image_raw'
        - '/camera/depth/image_rect_raw'
        - '/flir_boson/image_raw'
    pcl_topics:
        - '/velodyne_points'
        - '/mmWaveDataHdl/RScan_middle'
        - '/mmWaveDataHdl/RScan_left'
        - '/mmWaveDataHdl/RScan_right'
    csv_topics:
        - '/odom'
        - '/imu/data'
    thermal_16bit: True
    pcl2depth:
        mmwave_dist_min: 0.3
        mmwave_dist_max: 5
        h_fov: (-63, 63)
        h_multi_fov: (-126, 126)
        h_res: 2
        v_fov: (-30, 30)
        v_res: 2
        max_v: 6
        nb_overlay_frames: 3
    translation_matrix:
        middle: [0.16, 0, 0.0, 0, 0, 0]
        left: [0, 0.16, 0.0, 0, 0, 0.7071, 0.7071]
        right: [0, -0.16, 0.0, 0, 0, -0.7071, 0.7071]
    dataroot: '/media/lipeize/LaCie/Dataset/Oxford-rosbag/robot'
    milliego:
        saved_dir_h5: '/media/lipeize/LaCie/Dataset/Oxford-rosbag/milliego_h5'
        master: 'mmwave_all'
        slaves: # General rule: set the IMU as the last slave
             - 'imu'
        master_gap: 5 # for the master
    deeptio:
        saved_dir_h5: '/media/lipeize/LaCie/Dataset/Oxford-rosbag/deeptio_h5'
        master: 'thermal'
        slaves: # General rule: set the IMU as the last slave
             - 'imu'
        master_gap: 5 # for the master
    all_exp_files:
          - 2019-10-24-17-51-58
          - 2019-10-24-17-53-58
          - 2019-10-24-17-55-21
          - 2019-10-24-17-56-33
          - 2019-10-24-17-57-46
          - 2019-10-24-17-58-56
          - 2019-10-24-18-03-57
          - 2019-10-24-18-05-22
          - 2019-10-24-18-06-56
          - 2019-10-24-18-08-33
          - 2019-10-24-18-11-06
          - 2019-10-24-18-12-15
          - 2019-10-24-18-13-21
          - 2019-10-24-18-16-24
          - 2019-10-24-18-18-47
          - 2019-10-24-18-21-18
          - 2019-10-24-18-22-33
          - 2019-10-24-18-24-40
          - 2019-10-27-14-28-21
          - 2019-10-27-14-39-09
          - 2019-10-27-14-42-16
          - 2019-10-27-14-47-00
          - 2019-10-27-14-50-17
          - 2019-10-27-14-56-27
          - 2019-10-27-15-02-46
          - 2019-10-27-15-06-06
          - 2019-10-27-15-09-33
          - 2019-10-27-15-13-03
          - 2019-10-27-15-18-07
          - 2019-10-27-15-24-29
          - 2019-10-27-15-26-35
          - 2019-10-27-15-33-43
          - 2019-11-04-20-29-51
          - 2019-11-04-20-38-57
          - 2019-11-04-20-44-42
          - 2019-11-04-20-50-22
          - 2019-11-04-20-53-11
          - 2019-11-04-20-58-32
          - 2019-11-04-21-03-01
          - 2019-11-04-21-14-16
          - 2019-11-04-21-16-38
          - 2019-11-04-21-25-03
          - 2019-11-04-21-27-48
          - 2019-11-07-17-07-37
          - 2019-11-07-17-10-55
          - 2019-11-07-17-16-06
          - 2019-11-07-17-17-48
          - 2019-11-07-17-21-14
          - 2019-11-07-17-22-29
          - 2019-11-07-17-23-58
          - 2019-11-07-17-26-06
          - 2019-11-07-17-29-52
          - 2019-11-07-17-32-02
          - 2019-11-07-17-32-56
          - 2019-11-07-17-34-04
          - 2019-11-07-17-35-27
          - 2019-11-07-17-39-14
          - 2019-11-07-17-42-47
          - 2019-11-07-17-47-21
          - 2019-11-22-10-10-00
          - 2019-11-22-10-14-01
          - 2019-11-22-10-22-48
          - 2019-11-22-10-26-42
          - 2019-11-22-10-33-16
          - 2019-11-22-10-34-57
          - 2019-11-22-10-36-00
          - 2019-11-22-10-37-42
          - 2019-11-22-10-38-47
          - 2019-11-28-15-26-55
          - 2019-11-28-15-30-17
          - 2019-11-28-15-31-27
          - 2019-11-28-15-34-53
          - 2019-11-28-15-36-35
          - 2019-11-28-15-38-13
          - 2019-11-28-15-40-10
          - 2019-11-28-15-43-32


dataset_creation_drone:
    img_topics:
        - '/camera/color/image_raw'
        - '/camera/depth/image_rect_raw'
        - '/flir_boson/image_raw'
    pcl_topics:
        - '/velodyne_points'
        - '/ti_mmwave/radar_scan_pcl_0'
    csv_topics:
        - '/vrpn_client_node/X500_pglite/pose'
        - '/imu/data'
    thermal_16bit: False
    pcl2depth:
        mmwave_dist_min: 0.3
        mmwave_dist_max: 9
        h_fov: (-63, 63)
        h_res: 2
        v_fov: (-15, 15)
        v_res: 2
        max_v: 6
        nb_overlay_frames: 2
    dataroot: '/mnt/workdir/Dataset/Ox-Ed-rosbags/drone_batch2'
    milliego:
        saved_dir_h5: '/mnt/workdir/Dataset/Ox-Ed-rosbags/milliego_overlap'
        master: 'mmwave_middle' # the first/main data (single channel: thermal, mmwave, depth, lidar) that you synchronize with GT
        # master: 'mmwave'
        slaves: # General rule: set the IMU as the last slave
             - 'imu'
        master_gap: 2 # for the master
    deeptio:
        saved_dir_h5: '/media/lipeize/LaCie/Dataset/Oxford-rosbag/deeptio_h5'
        master: 'thermal'
        slaves: # General rule: set the IMU as the last slave
             - 'imu'
        master_gap: 2 # for the master
    all_exp_files:
        - 2022-01-20-00-09-47
        - 2022-01-20-00-14-36
        - 2022-01-20-00-28-19
        - 2022-01-20-02-15-11
        - 2022-01-20-02-35-23
        - 2022-02-08-19-30-42
        - 2022-02-08-19-57-51
        - 2022-02-08-20-06-17


dataset_creation_handheld:
    img_topics:
#        - '/camera/color/image_raw'
#        - '/camera/depth/image_rect_raw'
#        - '/flir_boson/image_raw'
    pcl_topics:
#        - '/velodyne_points'
        - '/mmWaveDataHdl/RScan_middle'
    csv_topics:
        - '/imu/data'
    gt_topics:
        - '/aft_mapped_to_init'
    thermal_16bit: True
    pcl2depth:
        mmwave_dist_min: 0.3
        mmwave_dist_max: 9
        h_fov: (-63, 63)
        h_res: 2
        v_fov: (-15, 15)
        v_res: 2
        max_v: 6
        nb_overlay_frames: 3
    dataroot: '/media/pi/BackupPlus/jhuai/data/odombeyondvision/rosbags/handheld'
    milliego:
        saved_dir_h5: '/home/pi/Documents/results/milliego/milliego_handheld_'
        master: 'mmwave_middle'
        slaves: # General rule: set the IMU as the last slave
             # - 'rgb'
             # - 'depth'
             - 'imu'
        master_gap: 4 # for the master
    deeptio:
        saved_dir_h5: '/home/pi/Documents/results/deeptio/deeptio_h5'
        master: 'thermal'
        slaves: # General rule: set the IMU as the last slave
             - 'imu'
        master_gap: 5 # for the master
    test_file_idx: 44 # the number of all_exp_files to be saved to h5 files.
    all_exp_files:
          - 2020-01-28-11-10-12
          - 2020-01-28-11-15-11
          - 2020-01-28-11-20-29
          - 2020-01-28-11-24-40
          - 2020-01-28-11-28-50
          - 2020-01-28-11-34-05
          - 2020-01-28-11-36-12
          - 2020-01-28-11-38-18
          - 2020-01-28-11-39-07
          - 2020-01-28-11-43-26
          - 2020-01-28-11-45-44
          - 2020-01-28-11-47-09
          - 2020-01-28-11-48-44
          - 2020-01-28-11-50-54
          - 2020-01-28-11-53-26
          - 2020-01-28-11-55-54
          - 2020-01-28-11-57-59
          - 2020-01-28-11-59-42
          - 2020-01-28-12-01-24
          - 2020-01-29-17-49-34
          - 2020-02-06-15-03-24
          - 2020-02-06-15-07-25
          - 2020-02-06-15-15-32
          - 2020-02-06-15-24-24
          - 2020-02-06-15-29-15
          - 2020-02-06-15-35-57
          - 2020-02-06-15-48-35
          - 2020-02-06-15-58-41
          - 2020-02-06-16-04-15
          - 2020-02-06-16-09-40
          - 2020-02-06-16-15-45
          - 2020-02-06-16-21-04
          - 2020-02-07-15-57-43
          - 2020-02-07-16-09-47
          - 2020-02-07-16-25-22
          - 2020-02-07-16-31-44
          - 2020-02-07-16-36-31
          - 2020-02-07-16-41-08
          - 2020-02-07-16-46-50
          - 2020-02-07-17-00-15
          - 2020-02-07-17-01-24
          - 2020-02-07-17-04-08
          - 2020-02-07-17-08-21
          - 2020-02-07-17-11-56
